"""Step service for AgentStep lifecycle management via NATS"""
import logging
from typing import Dict, Any, Optional
from internal.messaging.nats import get_nats_client

logger = logging.getLogger(__name__)


class StepService:
    """Service for managing AgentStep lifecycle via NATS messaging"""
    
    def __init__(self):
        self.nats = get_nats_client()
    
    async def create_step(
        self,
        run_id: str,
        phase: str,
        agent_name: str,
        input_data: Optional[Dict[str, Any]] = None,
        user_id: str = "system"
    ) -> str:
        """
        Send step creation event to agent-service via NATS
        
        Returns:
            step_id: The step ID (will be generated by agent-service)
        """
        # This is now a no-op - agent-service handles step lifecycle from state events
        # Kept for backward compatibility but does nothing
        return ""
    
    async def complete_step(
        self,
        step_id: str,
        output_data: Optional[Dict[str, Any]] = None,
        error_message: Optional[str] = None,
        user_id: str = "system",
        run_id: str = ""
    ) -> None:
        """
        Send step completion event to agent-service via NATS
        """
        # This is now a no-op - agent-service handles step lifecycle from state events
        # Kept for backward compatibility but does nothing
        pass


# Global step service instance
_step_service: Optional[StepService] = None


def get_step_service() -> StepService:
    """Get or create the global step service singleton"""
    global _step_service
    if _step_service is None:
        _step_service = StepService()
    return _step_service
